Repository Swift-Coding-Club/today-photo, pull requests merged in 2022-12, with the labels that each got.

#6 Feature/login 누락 코드 반영
  today-photo/.swiftlint.yml
  today-photo/today-photo.xcodeproj/project.pbxproj
  today-photo/today-photo/ContentView.swift
  today-photo/today-photo/UserAuthModel.swift
  today-photo/today-photo/View/LoginView.swift
  today-photo/today-photo/View/SettingView.swift
  today-photo/today-photo/View/TestView.swift
Labels: fix, 🍎이라

#7 Feature/writing diary UI
  today-photo/.swiftlint.yml
  today-photo/today-photo.xcodeproj/project.pbxproj
  today-photo/today-photo/Assets.xcassets/Screenshot 2022-11-07 at 11.31.02 PM.imageset/Contents.json
  today-photo/today-photo/Assets.xcassets/Screenshot 2022-11-07 at 11.31.02 PM.imageset/Screenshot 2022-11-07 at 11.31.02 PM.png
  today-photo/today-photo/View/WritingDiaryConnectionView.swift
  today-photo/today-photo/View/WritingDiaryView/Camera/CameraCoverView.swift
  today-photo/today-photo/View/WritingDiaryView/Camera/CameraView.swift
  today-photo/today-photo/View/WritingDiaryView/WritingDiaryView.swift
Labels: 😁드루

#10 Develop
  today-photo/.swiftlint.yml
  today-photo/today-photo.xcodeproj/project.pbxproj
  today-photo/today-photo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  today-photo/today-photo/Assets.xcassets/Screenshot 2022-11-07 at 11.31.02 PM.imageset/Contents.json
  today-photo/today-photo/Assets.xcassets/Screenshot 2022-11-07 at 11.31.02 PM.imageset/Screenshot 2022-11-07 at 11.31.02 PM.png
  today-photo/today-photo/Assets.xcassets/appLogo.imageset/Contents.json
  today-photo/today-photo/Assets.xcassets/appLogo.imageset/appLogo.svg
  today-photo/today-photo/Assets.xcassets/g-logo.imageset/Contents.json
  today-photo/today-photo/Assets.xcassets/g-logo.imageset/g-logo.png
  today-photo/today-photo/ContentView.swift
  today-photo/today-photo/UserAuthModel.swift
  today-photo/today-photo/View/LoginView.swift
  today-photo/today-photo/View/TestView.swift
  today-photo/today-photo/View/WritingDiaryConnectionView.swift
  today-photo/today-photo/View/WritingDiaryView/Camera/CameraCoverView.swift
  today-photo/today-photo/View/WritingDiaryView/Camera/CameraView.swift
  today-photo/today-photo/View/WritingDiaryView/WritingDiaryView.swift
  today-photo/today-photo/today_photoApp.swift
Labels: fix, 😁드루
